# Generated by Django 4.0.5 on 2022-06-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text1', models.TextField(max_length=10000)),
                ('input_text2', models.TextField(max_length=10000)),
                ('text1_count_out', models.TextField(max_length=10000)),
                ('text2_count_out', models.TextField(max_length=10000)),
                ('both_texts_IDF_TF_out', models.TextField(max_length=10000)),
            ],
        ),
    ]
